M48
; DRILL file {KiCad 9.0.4} date 2026-09-29T14:32:56+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-29T14:32:56+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X114.575Y-7.53
X119.425Y-7.53
T2
X114.275Y-4.5
X119.725Y-4.5
T3
X3.5Y-3.5
X3.5Y-86.5
X97.0Y-3.5
X131.5Y-86.5
M30
